version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: handyman-repairs
    ports:
      - "5555:5432"

  handyman-repairs:
    build:
      context: ../../../
      dockerfile: ./support/docker/handyman-repairs/Dockerfile
    image: handyman-repairs:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/handyman-repairs
    depends_on:
      - postgres