spring:
  application:
    name: handyman-repairs
  datasource:
    url: jdbc:postgresql://localhost:5555/handyman-repairs
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
#    defer-datasource-initialization: false
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:/db/data.sql
#      schema-locations: classpath:/db/schema.sql
#      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /api/v1