spring:
  application:
    name: handyman-repairs
  datasource:
    url: jdbc:postgresql://localhost:5555/handyman-repairs
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1